# Generated by Django 5.0.6 on 2024-06-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_activesubscriber_mrr_sale_unsubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandon', 'Abandon'), ('checkout', 'Checkout')], max_length=50),
        ),
    ]
